name: Security analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  security:
    uses: dvsa/.github/.github/workflows/php-security.yml@promote-php-actions
    with: 
     php_versions: "['7.4']"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}