name: Security analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  security:
    steps:
    - id: set-matrix
      run: echo "php_versions={\"include\":[\"7.4\", \"8.0\", \"8.1\"]}" >> $GITHUB_OUTPUT
 
    uses: dvsa/.github/.github/workflows/php-security.yml@promote-php-actions
    with: 
     php_versions: ${{ needs.security.outputs.matrix}}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}